const nros = {
    "0":"Los huevos",
    "1":"El agua",
    "2":"El niño",
    "3":"San Cono",
    "4":"La cama",
    "5":"El gato",
    "6":"El perro",
    "7":"El revólver",
    "8":"El incendio",
    "9":"El arroyo",
    "10":"El cañón",
    "11":"El minero",
    "12":"El soldado",
    "13":"La yeta",
    "14":"El borracho",
    "15":"La niña bonita",
    "16":"El anillo",
    "17":"La desgracia",
    "18":"La sangre",
    "19":"El pescado",
    "20":"La fiesta",
    "21":"La mujer",
    "22":"El loco",
    "23":"El cocinero",
    "24":"El caballo",
    "25":"La gallina"
};
console.log(nros[prompt("Ingrese un número de la quiniela: ")]);